preset: angular
repositoryUrl: https://github.com/mindulle/dev.git
branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/exec"
    # - publishCmd: |
    #     echo "${nextRelease.notes}" > /tmp/release-notes.md
    #     goreleaser release --release-notes /tmp/release-notes.md --clean
